<#
.SYNOPSIS
    Analyzes a GitHub Pull Request for AI-assisted code patterns

.DESCRIPTION
    Fetches PR diff directly from GitHub API and analyzes for AI patterns
    without needing to clone or merge the repository locally.

.PARAMETER PRUrl
    Full GitHub PR URL (e.g., "https://github.com/microsoft/repo/pull/123")

.PARAMETER RepoOwner
    GitHub repository owner (e.g., "microsoft")

.PARAMETER RepoName
    GitHub repository name

.PARAMETER PRNumber
    Pull Request number to analyze

.PARAMETER GitHubToken
    GitHub Personal Access Token (optional, but recommended for rate limits)

.EXAMPLE
    .\Analyze-GitHubPR.ps1 -PRUrl "https://github.com/microsoft/Multi-Agent-Custom-Automation-Engine-Solution-Accelerator/pull/753"

.EXAMPLE
    .\Analyze-GitHubPR.ps1 -RepoOwner "microsoft" -RepoName "Multi-Agent-Custom-Automation-Engine-Solution-Accelerator" -PRNumber 753
#>

[CmdletBinding()]
param(
    [Parameter(ParameterSetName='Url')]
    [string]$PRUrl,
    
    [Parameter(ParameterSetName='Parts', Mandatory=$true)]
    [string]$RepoOwner,
    
    [Parameter(ParameterSetName='Parts', Mandatory=$true)]
    [string]$RepoName,
    
    [Parameter(ParameterSetName='Parts', Mandatory=$true)]
    [int]$PRNumber,
    
    [Parameter()]
    [string]$GitHubToken = $env:GITHUB_TOKEN,
    
    [Parameter()]
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\reports\pr-analysis"),
    
    [Parameter()]
    [switch]$JsonOutput
)

# Parse URL if provided
if ($PRUrl) {
    if ($PRUrl -match 'github\.com/([^/]+)/([^/]+)/pull/(\d+)') {
        $RepoOwner = $Matches[1]
        $RepoName = $Matches[2]
        $PRNumber = [int]$Matches[3]
    } else {
        Write-Error "Invalid PR URL format. Expected: https://github.com/owner/repo/pull/123"
        exit 1
    }
}

Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║     GitHub PR Analysis - 5-Tier AI Detection Model        ║" -ForegroundColor Cyan
Write-Host "╚═══════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""
Write-Host "Repository: $RepoOwner/$RepoName" -ForegroundColor Yellow
Write-Host "PR Number:  #$PRNumber" -ForegroundColor Yellow
Write-Host ""

# =====================================================
# 5-TIER AI DETECTION PATTERNS
# =====================================================

$tier1Patterns = @(
    @{ Pattern = 'GitHub Copilot'; Weight = 100; Name = 'Copilot mention' },
    @{ Pattern = 'Generated by Copilot'; Weight = 100; Name = 'Generated by Copilot' },
    @{ Pattern = 'Co-authored-by:.*[Cc]opilot'; Weight = 100; Name = 'Co-authored-by Copilot' },
    @{ Pattern = '\[AI\]'; Weight = 100; Name = 'AI tag' },
    @{ Pattern = '\[copilot\]'; Weight = 100; Name = 'Copilot tag' },
    @{ Pattern = '#\s*AI generated'; Weight = 100; Name = 'AI generated comment' },
    @{ Pattern = '//\s*copilot'; Weight = 100; Name = 'Copilot comment' },
    @{ Pattern = 'auto-generated'; Weight = 95; Name = 'Auto-generated' },
    @{ Pattern = '@ai-assisted'; Weight = 100; Name = 'AI-assisted decorator' },
    @{ Pattern = 'AI-generated'; Weight = 100; Name = 'AI-generated marker' }
)

$tier2Patterns = @(
    @{ Pattern = '//\s*[A-Z][a-z]+\s+the\s+\w+\s+(to|from|for|with)\s+'; Weight = 20; Name = 'AI-style verbose comment' },
    @{ Pattern = '#\s*[A-Z][a-z]+\s+the\s+\w+\s+(to|from|for|with)\s+'; Weight = 20; Name = 'AI-style Python comment' },
    @{ Pattern = 'try\s*\{[\s\S]{30,}catch[\s\S]{10,}finally'; Weight = 18; Name = 'Comprehensive try-catch-finally' },
    @{ Pattern = 'ArgumentNullException.*nameof'; Weight = 15; Name = 'ArgumentNullException with nameof' },
    @{ Pattern = 'if\s*\(\s*string\.IsNullOrEmpty\s*\([^)]+\)\s*\)\s*throw'; Weight = 18; Name = 'Null check with throw' },
    @{ Pattern = 'if\s*\(\s*string\.IsNullOrWhiteSpace\s*\([^)]+\)\s*\)\s*throw'; Weight = 18; Name = 'Whitespace check with throw' },
    @{ Pattern = '\$result\d+'; Weight = 15; Name = 'Numbered result variable' },
    @{ Pattern = '\$response\d+'; Weight = 15; Name = 'Numbered response variable' },
    @{ Pattern = 'var result\d*\s*='; Weight = 12; Name = 'Generic result variable' },
    @{ Pattern = 'const response\d*\s*='; Weight = 12; Name = 'Generic response const' },
    @{ Pattern = 'throw new ArgumentException\(.*paramName'; Weight = 18; Name = 'ArgumentException with paramName' },
    @{ Pattern = '\.ConfigureAwait\(false\)'; Weight = 15; Name = 'ConfigureAwait(false)' },
    @{ Pattern = 'createAsyncThunk\s*\('; Weight = 18; Name = 'Redux createAsyncThunk' },
    @{ Pattern = 'extraReducers:\s*\(builder\)'; Weight = 20; Name = 'Redux extraReducers builder' },
    @{ Pattern = '\.addCase\(\w+\.(pending|fulfilled|rejected)'; Weight = 15; Name = 'Redux addCase pattern' },
    @{ Pattern = 'createSlice\s*\(\s*\{'; Weight = 15; Name = 'Redux createSlice' }
)

$tier3Patterns = @(
    @{ Pattern = 'catch\s*\(\s*Exception\s+\w+\s*\)'; Weight = 12; Name = 'Generic exception catch' },
    @{ Pattern = '\?\?\s*throw\s+new'; Weight = 10; Name = 'Null coalescing throw' },
    @{ Pattern = 'await\s+Task\.WhenAll'; Weight = 10; Name = 'Task.WhenAll' },
    @{ Pattern = 'await\s+Task\.WhenAny'; Weight = 10; Name = 'Task.WhenAny' },
    @{ Pattern = 'async\s+Task<[^>]+>\s+\w+Async\s*\('; Weight = 8; Name = 'Async method naming' },
    @{ Pattern = 'useCallback<[^>]+>\s*\('; Weight = 10; Name = 'useCallback with generic' },
    @{ Pattern = 'useMemo<[^>]+>\s*\('; Weight = 10; Name = 'useMemo with generic' },
    @{ Pattern = 'React\.FC<\w+Props>'; Weight = 8; Name = 'React.FC with Props' },
    @{ Pattern = '_logger\.Log(Information|Warning|Error|Debug)'; Weight = 10; Name = 'Structured logging' },
    @{ Pattern = 'ILogger<\w+>\s+_logger'; Weight = 8; Name = 'ILogger injection' },
    @{ Pattern = 'def\s+\w+\([^)]*:\s*\w+[^)]*\)\s*->\s*\w+:'; Weight = 8; Name = 'Python type hints' },
    @{ Pattern = 'useAppDispatch|useAppSelector'; Weight = 8; Name = 'Redux typed hooks' },
    @{ Pattern = '\.unwrap\(\)\.then\('; Weight = 12; Name = 'Redux unwrap pattern' }
)

$tier4Patterns = @(
    @{ Pattern = '\?\.'; Weight = 5; Name = 'Null conditional' },
    @{ Pattern = '\?\?='; Weight = 5; Name = 'Null coalescing assignment' },
    @{ Pattern = 'record\s+\w+\s*\('; Weight = 5; Name = 'C# record type' },
    @{ Pattern = 'IOptions<\w+>'; Weight = 4; Name = 'Options pattern' },
    @{ Pattern = 'AddScoped<\w+,\s*\w+>'; Weight = 4; Name = 'DI AddScoped' },
    @{ Pattern = 'AddTransient<\w+,\s*\w+>'; Weight = 4; Name = 'DI AddTransient' },
    @{ Pattern = 'AddSingleton<\w+,\s*\w+>'; Weight = 4; Name = 'DI AddSingleton' },
    @{ Pattern = 'interface\s+\w+Props\s*\{'; Weight = 5; Name = 'Props interface' },
    @{ Pattern = 'useState<[^>]+>\s*\('; Weight = 5; Name = 'useState with type' },
    @{ Pattern = 'useEffect\s*\(\s*\(\)\s*=>\s*\{'; Weight = 5; Name = 'useEffect hook' },
    @{ Pattern = 'Optional\[\w+\]'; Weight = 5; Name = 'Python Optional' },
    @{ Pattern = '@dataclass'; Weight = 5; Name = 'Python dataclass' },
    @{ Pattern = 'reducers:\s*\{'; Weight = 5; Name = 'Redux reducers' },
    @{ Pattern = 'export const \w+Slice\s*='; Weight = 7; Name = 'Redux slice export' }
)

$tier5Patterns = @(
    @{ Pattern = '\?\.\w+'; Weight = 2; Name = 'Optional chaining' },
    @{ Pattern = '\?\?'; Weight = 2; Name = 'Null coalescing' },
    @{ Pattern = 'await\s+\w+'; Weight = 2; Name = 'Basic await' },
    @{ Pattern = '\.map\(\w+\s*=>'; Weight = 2; Name = 'Arrow in map' },
    @{ Pattern = '\.filter\(\w+\s*=>'; Weight = 2; Name = 'Arrow in filter' },
    @{ Pattern = '\.reduce\(\s*\('; Weight = 2; Name = 'Reduce pattern' },
    @{ Pattern = 'const\s+\w+\s*=\s*async'; Weight = 3; Name = 'Async arrow function' },
    @{ Pattern = '@property'; Weight = 2; Name = 'Python property' },
    @{ Pattern = 'f"[^"]*\{[^}]+\}'; Weight = 2; Name = 'Python f-string' },
    @{ Pattern = 'List\[\w+\]'; Weight = 2; Name = 'Python List type' },
    @{ Pattern = 'Dict\[\w+,\s*\w+\]'; Weight = 2; Name = 'Python Dict type' }
)

# Excluded file patterns
# NOTE: Empty by default - all files are analyzed. Add patterns here if needed:
# Example patterns:
#   '\.test\.(ts|tsx|js|jsx)$' - Test files
#   '\.spec\.(ts|tsx|js|jsx)$' - Spec files
#   'tests?/'                   - Test directories
#   '__tests__/'                - Jest test directories
#   'package-lock\.json$'      - Lock files
$excludeFilePatterns = @(
    # Add exclusion patterns here if needed
)

# =====================================================
# GITHUB API FUNCTIONS
# =====================================================

function Get-GitHubHeaders {
    $headers = @{
        'Accept' = 'application/vnd.github.v3+json'
        'User-Agent' = 'CopilotUsageAnalyzer/1.0'
    }
    if ($GitHubToken) {
        $headers['Authorization'] = "token $GitHubToken"
    }
    return $headers
}

function Get-PRDetails {
    param([string]$Owner, [string]$Repo, [int]$PR)
    
    $url = "https://api.github.com/repos/$Owner/$Repo/pulls/$PR"
    try {
        $response = Invoke-RestMethod -Uri $url -Headers (Get-GitHubHeaders) -Method Get
        return $response
    } catch {
        Write-Error "Failed to fetch PR details: $_"
        return $null
    }
}

function Get-PRFiles {
    param([string]$Owner, [string]$Repo, [int]$PR)
    
    $url = "https://api.github.com/repos/$Owner/$Repo/pulls/$PR/files?per_page=100"
    $allFiles = @()
    
    try {
        do {
            $response = Invoke-WebRequest -Uri $url -Headers (Get-GitHubHeaders) -Method Get
            $files = $response.Content | ConvertFrom-Json
            $allFiles += $files
            
            # Check for pagination
            $linkHeader = $response.Headers['Link']
            if ($linkHeader -and $linkHeader -match '<([^>]+)>;\s*rel="next"') {
                $url = $Matches[1]
            } else {
                $url = $null
            }
        } while ($url)
        
        return $allFiles
    } catch {
        Write-Error "Failed to fetch PR files: $_"
        return @()
    }
}

function Get-PRCommits {
    param([string]$Owner, [string]$Repo, [int]$PR)
    
    $url = "https://api.github.com/repos/$Owner/$Repo/pulls/$PR/commits?per_page=100"
    try {
        $response = Invoke-RestMethod -Uri $url -Headers (Get-GitHubHeaders) -Method Get
        return $response
    } catch {
        Write-Error "Failed to fetch PR commits: $_"
        return @()
    }
}

# =====================================================
# ANALYSIS FUNCTIONS
# =====================================================

function Test-ExcludedFile {
    param([string]$FileName)
    
    foreach ($pattern in $excludeFilePatterns) {
        if ($FileName -match $pattern) {
            return $true
        }
    }
    return $false
}

function Get-PatternMatches {
    param(
        [string]$Content,
        [array]$Patterns
    )
    
    $matches = @()
    $totalWeight = 0
    
    foreach ($patternDef in $Patterns) {
        $regex = [regex]::new($patternDef.Pattern, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
        $found = $regex.Matches($Content)
        
        if ($found.Count -gt 0) {
            $matches += [PSCustomObject]@{
                Pattern = $patternDef.Name
                Count = $found.Count
                Weight = $patternDef.Weight
                TotalWeight = $found.Count * $patternDef.Weight
            }
            $totalWeight += ($found.Count * $patternDef.Weight)
        }
    }
    
    return @{
        Matches = $matches
        TotalWeight = $totalWeight
    }
}

function Analyze-FileContent {
    param(
        [string]$Patch,
        [string]$FileName
    )
    
    if (-not $Patch) { return $null }
    
    # Extract only added lines (lines starting with +, but not +++)
    $addedLines = ($Patch -split "`n" | Where-Object { $_ -match '^\+[^\+]' }) -join "`n"
    $addedLineCount = ($Patch -split "`n" | Where-Object { $_ -match '^\+[^\+]' }).Count
    
    if ($addedLineCount -eq 0) { return $null }
    
    # Analyze each tier
    $tier1 = Get-PatternMatches -Content $addedLines -Patterns $tier1Patterns
    $tier2 = Get-PatternMatches -Content $addedLines -Patterns $tier2Patterns
    $tier3 = Get-PatternMatches -Content $addedLines -Patterns $tier3Patterns
    $tier4 = Get-PatternMatches -Content $addedLines -Patterns $tier4Patterns
    $tier5 = Get-PatternMatches -Content $addedLines -Patterns $tier5Patterns
    
    $totalWeight = $tier1.TotalWeight + $tier2.TotalWeight + $tier3.TotalWeight + $tier4.TotalWeight + $tier5.TotalWeight
    $patternDensity = if ($addedLineCount -gt 0) { ($totalWeight / $addedLineCount) * 100 } else { 0 }
    
    # Determine tier and confidence
    $tierNumber = 0
    $confidence = 0
    $tierName = "Human Written"
    
    if ($tier1.TotalWeight -gt 0) {
        $tierNumber = 1
        $confidence = 99
        $tierName = "Tier 1: Definitive AI"
    } elseif ($tier2.TotalWeight -ge 40 -and $patternDensity -ge 2.0) {
        $tierNumber = 2
        $confidence = 95
        $tierName = "Tier 2: Very High Confidence"
    } elseif (($tier2.TotalWeight + $tier3.TotalWeight) -ge 35 -and $patternDensity -ge 2.0) {
        $tierNumber = 3
        $confidence = 85
        $tierName = "Tier 3: High Confidence"
    } elseif (($tier2.TotalWeight + $tier3.TotalWeight + $tier4.TotalWeight) -ge 25 -and $patternDensity -ge 1.5) {
        $tierNumber = 4
        $confidence = 75
        $tierName = "Tier 4: Moderate Confidence"
    } elseif ($totalWeight -ge 15 -and $patternDensity -ge 1.0) {
        $tierNumber = 5
        $confidence = 65
        $tierName = "Tier 5: Low Confidence"
    }
    
    return [PSCustomObject]@{
        FileName = $FileName
        LinesAdded = $addedLineCount
        TotalWeight = $totalWeight
        PatternDensity = [math]::Round($patternDensity, 2)
        TierNumber = $tierNumber
        Confidence = $confidence
        TierName = $tierName
        IsAI = $tierNumber -gt 0
        Tier1Matches = $tier1.Matches
        Tier2Matches = $tier2.Matches
        Tier3Matches = $tier3.Matches
        Tier4Matches = $tier4.Matches
        Tier5Matches = $tier5.Matches
    }
}

# =====================================================
# MAIN ANALYSIS
# =====================================================

Write-Host "Fetching PR details..." -ForegroundColor Gray

# Get PR details
$prDetails = Get-PRDetails -Owner $RepoOwner -Repo $RepoName -PR $PRNumber
if (-not $prDetails) {
    Write-Error "Could not fetch PR details. Check the PR URL and your GitHub token."
    exit 1
}

Write-Host "  Title: $($prDetails.title)" -ForegroundColor White
Write-Host "  Author: $($prDetails.user.login)" -ForegroundColor White
Write-Host "  State: $($prDetails.state)" -ForegroundColor White
Write-Host "  Created: $($prDetails.created_at)" -ForegroundColor White
Write-Host ""

# Get PR files
Write-Host "Fetching PR files..." -ForegroundColor Gray
$prFiles = Get-PRFiles -Owner $RepoOwner -Repo $RepoName -PR $PRNumber
Write-Host "  Found $($prFiles.Count) file(s)" -ForegroundColor White
Write-Host ""

# Get PR commits
Write-Host "Fetching PR commits..." -ForegroundColor Gray
$prCommits = Get-PRCommits -Owner $RepoOwner -Repo $RepoName -PR $PRNumber
Write-Host "  Found $($prCommits.Count) commit(s)" -ForegroundColor White
Write-Host ""

# Analyze files
Write-Host "Analyzing files for AI patterns..." -ForegroundColor Cyan
Write-Host ""

$fileResults = @()
$totalLinesAdded = 0
$aiLinesAdded = 0
$skippedFiles = 0

foreach ($file in $prFiles) {
    $fileName = $file.filename
    
    # Skip excluded files
    if (Test-ExcludedFile -FileName $fileName) {
        $skippedFiles++
        continue
    }
    
    # Skip deleted files
    if ($file.status -eq 'removed') {
        continue
    }
    
    $result = Analyze-FileContent -Patch $file.patch -FileName $fileName
    
    if ($result) {
        $fileResults += $result
        $totalLinesAdded += $result.LinesAdded
        
        if ($result.IsAI) {
            $aiLinesAdded += $result.LinesAdded
        }
        
        # Display result
        $color = switch ($result.TierNumber) {
            1 { 'Red' }
            2 { 'Magenta' }
            3 { 'Yellow' }
            4 { 'Cyan' }
            5 { 'Blue' }
            default { 'Gray' }
        }
        
        $tierLabel = if ($result.TierNumber -gt 0) { "Tier $($result.TierNumber)" } else { "Human" }
        Write-Host "  [$tierLabel] " -ForegroundColor $color -NoNewline
        Write-Host "$fileName " -NoNewline
        Write-Host "(+$($result.LinesAdded) lines, score: $($result.TotalWeight))" -ForegroundColor DarkGray
    }
}

# Calculate summary
$aiPercentage = if ($totalLinesAdded -gt 0) { [math]::Round(($aiLinesAdded / $totalLinesAdded) * 100, 2) } else { 0 }
$aiFileCount = ($fileResults | Where-Object { $_.IsAI }).Count
$humanFileCount = ($fileResults | Where-Object { -not $_.IsAI }).Count

# Tier distribution
$tier1Files = ($fileResults | Where-Object { $_.TierNumber -eq 1 }).Count
$tier2Files = ($fileResults | Where-Object { $_.TierNumber -eq 2 }).Count
$tier3Files = ($fileResults | Where-Object { $_.TierNumber -eq 3 }).Count
$tier4Files = ($fileResults | Where-Object { $_.TierNumber -eq 4 }).Count
$tier5Files = ($fileResults | Where-Object { $_.TierNumber -eq 5 }).Count

# Display summary
Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "                    ANALYSIS RESULTS                        " -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "PR: $RepoOwner/$RepoName#$PRNumber" -ForegroundColor White
Write-Host "Title: $($prDetails.title)" -ForegroundColor White
Write-Host "Author: $($prDetails.user.login)" -ForegroundColor White
Write-Host ""
Write-Host "Files Analyzed: $($fileResults.Count)" -ForegroundColor White
Write-Host "Files Skipped (tests/config): $skippedFiles" -ForegroundColor DarkGray
Write-Host ""
Write-Host "Lines Added: $totalLinesAdded" -ForegroundColor White
Write-Host "AI-Assisted Lines: $aiLinesAdded ($aiPercentage%)" -ForegroundColor $(if ($aiPercentage -ge 50) { 'Green' } else { 'Yellow' })
Write-Host ""
Write-Host "Tier Distribution:" -ForegroundColor White
Write-Host "  Tier 1 (Definitive):   $tier1Files files" -ForegroundColor Red
Write-Host "  Tier 2 (Very High):    $tier2Files files" -ForegroundColor Magenta
Write-Host "  Tier 3 (High):         $tier3Files files" -ForegroundColor Yellow
Write-Host "  Tier 4 (Moderate):     $tier4Files files" -ForegroundColor Cyan
Write-Host "  Tier 5 (Low):          $tier5Files files" -ForegroundColor Blue
Write-Host "  Human Written:         $humanFileCount files" -ForegroundColor Gray
Write-Host ""

# Create output directory
if (-not (Test-Path $OutputPath)) {
    New-Item -ItemType Directory -Path $OutputPath -Force | Out-Null
}

# Generate JSON output
$analysisResult = [PSCustomObject]@{
    AnalysisDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Repository = "$RepoOwner/$RepoName"
    PRNumber = $PRNumber
    PRTitle = $prDetails.title
    PRAuthor = $prDetails.user.login
    PRState = $prDetails.state
    PRCreated = $prDetails.created_at
    PRUrl = "https://github.com/$RepoOwner/$RepoName/pull/$PRNumber"
    Summary = @{
        TotalFiles = $fileResults.Count
        SkippedFiles = $skippedFiles
        TotalLinesAdded = $totalLinesAdded
        AILinesAdded = $aiLinesAdded
        AIPercentage = $aiPercentage
        AIFileCount = $aiFileCount
        HumanFileCount = $humanFileCount
        TierDistribution = @{
            Tier1 = $tier1Files
            Tier2 = $tier2Files
            Tier3 = $tier3Files
            Tier4 = $tier4Files
            Tier5 = $tier5Files
            Human = $humanFileCount
        }
    }
    CommitCount = $prCommits.Count
    Commits = $prCommits | ForEach-Object {
        @{
            SHA = $_.sha
            Author = $_.commit.author.name
            Message = $_.commit.message
            Date = $_.commit.author.date
        }
    }
    FileAnalysis = $fileResults
}

$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$jsonPath = Join-Path $OutputPath "PR-$PRNumber`_$timestamp.json"
$analysisResult | ConvertTo-Json -Depth 10 | Set-Content $jsonPath -Encoding UTF8

Write-Host "Report saved: $jsonPath" -ForegroundColor Green

# Output JSON if requested
if ($JsonOutput) {
    $analysisResult | ConvertTo-Json -Depth 10
}

# Return result object
return $analysisResult
